// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiF7I0l6RaEbeF0gOf0ywPWqRG2zuRGNs',
    appId: '1:837643959794:android:95fac484150dca88797f6b',
    messagingSenderId: '837643959794',
    projectId: 'daconnect-f38a6',
    storageBucket: 'daconnect-f38a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ZEY1Eet70JEmU0b92WbAqCftJw2Jg8E',
    appId: '1:837643959794:ios:aca4c36f41a2eb20797f6b',
    messagingSenderId: '837643959794',
    projectId: 'daconnect-f38a6',
    storageBucket: 'daconnect-f38a6.firebasestorage.app',
    androidClientId: '837643959794-b1sjtpdmo54vo4u1b74q29ehqm454cp5.apps.googleusercontent.com',
    iosClientId: '837643959794-0dgi2pr8b67b492b008j6skljmb4l1s7.apps.googleusercontent.com',
    iosBundleId: 'com.jconnectApp',
  );
}
